name: hello
on:
  workflow_dispatch:
jobs:
  basic-ubuntu-20:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: helloworld
        run: echo "Hello World"
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.10"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"  
      - name: CDK Action
        # You may pin to the exact commit or the version.
        # uses: runbooksolutions/cdk-action@9434c6486a0cf642c694580f0d6bb1e3db1c16c4
        uses: runbooksolutions/cdk-action@v1.0.0
        with:
          # If the action needs to install cdk or if it is already globally
          install_cdk: true
      - name: Check CDK Installation
        run: cdk --version
        
                
