name: Reusable Workflow

on:
  workflow_dispatch:
  workflow_call:
jobs:
  call_reusable_workflow:
    uses: STDineshKumar/testingnext/.github/workflows/testingnext.yml@main
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Input
        run: echo "Input received call testing from master branch"
